require:
  - rubocop-rails
  - rubocop-performance

AllCops:
  TargetRubyVersion: 3.0
  Exclude:
    - 'db/schema.rb'
    - 'db/migrate/*'
    - !ruby/regexp /old_and_unused\.rb$/
    - 'bin/*'
    - 'node_modules/**/*'
    - 'public/**/*'
    - 'tmp/**/*'
    - 'log/**/*'

Rails:
  Enabled: true

# ドキュメントの無い public class を許可する
Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Max: 30

Metrics/AbcSize:
  Max: 24

Rails/SkipsModelValidations:
  Exclude:
    - 'app/models/user.rb'
    
Metrics/BlockLength:
  Max: 50

Rails/HelperInstanceVariable:
  Exclude:
    - 'app/helpers/sessions_helper.rb'

Metrics/MethodLength:
  Max: 20

Rails/OutputSafety:
  Exclude: 
    - 'app/helpers/markdown_helper.rb'