require:
  - rubocop-rails
  - rubocop-performance

AllCops:
  Exclude:
    - 'db/schema.rb'
    - 'db/migrate/*'
    - !ruby/regexp /old_and_unused\.rb$/
    - 'bin/*'
    - 'node_modules/**/*'
    - 'public/**/*'
    - 'tmp/**/*'
    - 'log/**/*'

Rails:
  Enabled: true

# ドキュメントの無い public class を許可する
Style/Documentation:
  Enabled: false